Generalize Drive impls for collection types
nikis05/derive-visitor pull request #4
Opened 2022-07-17 19:12 UTC by badicsalex

With this rewrite, basically all collection types are automatically supported without the need to write code manually.

Unfortunately this is a breaking change, because it is a conflicting trait impl if someone has already made a custom impl for their collection class with iterates over references of Drive-able items.

2022-07-18 02:19 UTC, nikis05 commented
Thanks for your contribution!

This seems like a reasonable change considering the following:
1. Crate users would still be able to implement their own collection iteration logic using `#[drive(with = "...")]`
2. This crate is small so collection libraries will never provide implementations of `Drive`
3. Implementing `Drive` on foreign collections for end users would be painful because of the orphan rule.

I will review this and hopefully merge soon.

2022-07-18 21:23 UTC, nikis05 requested changes
LGTM, unless you want to add something else, can you bump version to 0.2.1 on both packages and I'll merge it?

2022-07-19 19:21 UTC, badicsalex commented
I bumped the versions.

I also added Range, RangeInclusive, etc. to the std-types implementations, because that would make my life easier in my other project. Hope it's not a problem.

Thanks for being so responsive and open about these stuff.

2022-07-19 19:26 UTC, badicsalex commented
Hmm, apparently this doesn't work with Vec<String>, I'll have to check why.

2022-07-19 20:16 UTC, nikis05 approved these changes
Nice, thanks!

2022-07-19 20:19 UTC, merged